package database;

public enum SqlConstants {
    PROJECT_CONFIG_INFORMATION_INSERT,
    PROJECT_CONFIG_INFORMATION_LIST,
    PROJECT_CONFIG_PARAMTER_INSERT,
    PROJECT_CONFIG_PARAMTER_LIST,
    PROJECT_CONFIG_INFORMATION_UPDATE,
    PROJECT_CONFIG_PARAMTER_DELETE,
    SDK_INFO_INSERT,
    SDK_LIST_INSERT,
    SDK_INFO_LIST,
    SDK_LIST_LIST,
    SDK_INFO_UPDATE,
    SDK_LIST_DELETE,
    PROJECT_CONFIG_PUBLISH_LIST,
    PROJECT_CONFIG_INFORMATION_DELETE,
    PROJECT_CONFIG_LIST_DELETE_BYID,
    PROJECT_CONFIG_INFORMATION_COUNT,
    OPERATION_LOG
}
