package database;

public enum SqlConstants {
    PROJECT_CONFIG_INFORMATION_INSERT,
    PROJECT_CONFIG_INFORMATION_LIST,
    PROJECT_CONFIG_PARAMTER_INSERT,
    PROJECT_CONFIG_PARAMTER_LIST,
    PROJECT_CONFIG_INFORMATION_UPDATE,
    PROJECT_CONFIG_PARAMTER_DELETE,
    SDK_INFO_INSERT,
    SDK_LIST_INSERT,
    SDK_INFO_LIST,
    SDK_LIST_LIST,
    SDK_INFO_UPDATE,
    SDK_LIST_DELETE,
    PROJECT_CONFIG_PUBLISH_LIST,
    PROJECT_CONFIG_INFORMATION_DELETE,
    PROJECT_CONFIG_LIST_DELETE_BYID,
    PROJECT_CONFIG_INFORMATION_COUNT,
    OPERATION_LOG,
    API_PROJECT_LIST,
    API_SDK_LIST,
    API_PROJECT_LIST_NEW,
    API_SDK_LIST_NEW,
    ADD_COMPANY_INFO,
    EDIT_COMPANY_INFO,
    LIST_COMPANY_INFO

}
