package database;

public enum SqlConstants {
    OPERATION_LOG,
    FODDERINFO_INSERT,
    FODDERINFO_LIST,
    EDIT_CHANNEL_PROMO_EDIT,
    ADD_CHANNEL_PROMO_EDIT,
    GET_CHANNEL_PROMO_EDIT,
    GET_PROMO_CHANNEL,
    ADD_PROMO_CHANNEL,
    EDIT_PROMO_CHANNEL,
    GET_PROMO_LIST,
    ADD_PROMO_LIST,
    EDIT_PROMO_LIST,
    DEL_PROMO_LIST,
    GET_MAX_ID,
    ADD_PROMO_LIST_RECORD,
    GET_MAX_IDS,
    GET_ROW_PROMO_LIST,
    DEL_QINIU_FILE_RECORD,
    LIST_CHANNELPROMO_LIST_RECORD
}
